//! Asynchronous stream subscriptions owned by a component.

use std::any::Any;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

use futures_util::StreamExt;
use tokio::sync::{mpsc::UnboundedSender, watch};

use crate::context::{Context, RuntimeState};
use crate::entity::{EntityId, EntityStore};
use crate::task::TaskDelivery;

/// A stream item or the stream's normal end.
pub enum SubscriptionEvent<T> {
    /// An item yielded by the stream.
    Item(T),
    /// The stream ended normally.
    Closed,
}

/// A cancellation handle for a stream subscription.
#[derive(Debug)]
pub struct Subscription {
    active: Arc<AtomicBool>,
    cancellation: watch::Sender<bool>,
}

impl Subscription {
    pub(crate) fn new(active: Arc<AtomicBool>, cancellation: watch::Sender<bool>) -> Self {
        Self {
            active,
            cancellation,
        }
    }

    /// Cancel the subscription. This operation is idempotent.
    pub fn cancel(&self) {
        if self.active.swap(false, Ordering::Release) {
            let _ = self.cancellation.send(true);
        }
    }

    /// Returns whether the subscription is still active.
    pub fn is_active(&self) -> bool {
        self.active.load(Ordering::Acquire)
    }
}

impl Drop for Subscription {
    fn drop(&mut self) {
        self.cancel();
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) struct SubscriptionId(u64);

impl SubscriptionId {
    pub(crate) fn allocate() -> Self {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        Self(NEXT.fetch_add(1, Ordering::Relaxed))
    }
}

/// A runtime delivery generated by either a task or subscription.
pub enum RuntimeDelivery<M> {
    Task(TaskDelivery<M>),
    Subscription(SubscriptionDelivery),
}

/// A subscription delivery. Its target is resolved through the runtime registry.
pub struct SubscriptionDelivery {
    pub(crate) id: SubscriptionId,
    pub(crate) event: SubscriptionDeliveryEvent,
}

pub enum SubscriptionDeliveryEvent {
    Item(Box<dyn Any + Send>),
    Closed,
}

pub(crate) struct SubscriptionRecord<A, M> {
    pub(crate) target: EntityId,
    pub(crate) active: Arc<AtomicBool>,
    pub(crate) cancellation: watch::Sender<bool>,
    pub(crate) handler: Box<dyn SubscriptionHandler<A, M>>,
}

pub(crate) trait SubscriptionHandler<A, M>: 'static {
    fn invoke(
        &mut self,
        item: Box<dyn Any + Send>,
        target: EntityId,
        runtime_state: &mut RuntimeState<A, M>,
        store: &EntityStore<A, M>,
    );

    fn close(
        &mut self,
        target: EntityId,
        runtime_state: &mut RuntimeState<A, M>,
        store: &EntityStore<A, M>,
    );
}

struct TypedHandler<T, Item, F> {
    callback: F,
    marker: std::marker::PhantomData<fn(T, Item)>,
}

impl<T, Item, F, A, M> SubscriptionHandler<A, M> for TypedHandler<T, Item, F>
where
    T: crate::component::Component<A, M>,
    A: 'static,
    M: 'static,
    Item: 'static,
    F: for<'a> FnMut(SubscriptionEvent<Item>, &'a mut T, &'a mut Context<'a, T, A, M>) + 'static,
{
    fn invoke(
        &mut self,
        item: Box<dyn Any + Send>,
        target: EntityId,
        runtime_state: &mut RuntimeState<A, M>,
        store: &EntityStore<A, M>,
    ) {
        let Ok(item) = item.downcast::<Item>() else {
            return;
        };
        let Some(mut slot) = store.lock(target) else {
            return;
        };
        let Some(component) = slot
            .as_mut()
            .and_then(|value| value.as_any_mut().downcast_mut::<T>())
        else {
            return;
        };
        let mut cx = Context::new(runtime_state, store, target);
        (self.callback)(SubscriptionEvent::Item(*item), component, &mut cx);
    }

    fn close(
        &mut self,
        target: EntityId,
        runtime_state: &mut RuntimeState<A, M>,
        store: &EntityStore<A, M>,
    ) {
        let Some(mut slot) = store.lock(target) else {
            return;
        };
        let Some(component) = slot
            .as_mut()
            .and_then(|value| value.as_any_mut().downcast_mut::<T>())
        else {
            return;
        };
        let mut cx = Context::new(runtime_state, store, target);
        (self.callback)(SubscriptionEvent::Closed, component, &mut cx);
    }
}

pub(crate) fn handler<T, Item, F, A, M>(callback: F) -> Box<dyn SubscriptionHandler<A, M>>
where
    T: crate::component::Component<A, M>,
    A: 'static,
    M: 'static,
    Item: 'static,
    F: for<'a> FnMut(SubscriptionEvent<Item>, &'a mut T, &'a mut Context<'a, T, A, M>) + 'static,
{
    Box::new(TypedHandler {
        callback,
        marker: std::marker::PhantomData,
    })
}

pub(crate) async fn worker<S, Item, M>(
    stream: S,
    id: SubscriptionId,
    active: Arc<AtomicBool>,
    mut cancellation: watch::Receiver<bool>,
    sender: UnboundedSender<RuntimeDelivery<M>>,
) where
    S: futures_util::Stream<Item = Item> + Send + 'static,
    Item: Send + 'static,
    M: Send + 'static,
{
    let mut stream = Box::pin(stream);
    loop {
        tokio::select! {
            changed = cancellation.changed() => {
                if changed.is_err() || *cancellation.borrow() { break; }
            }
            item = stream.next() => {
                match item {
                    Some(item) => {
                        if !active.load(Ordering::Acquire) { break; }
                        if sender.send(RuntimeDelivery::Subscription(SubscriptionDelivery {
                            id,
                            event: SubscriptionDeliveryEvent::Item(Box::new(item)),
                        })).is_err() { break; }
                    }
                    None => {
                        if active.load(Ordering::Acquire) {
                            let _ = sender.send(RuntimeDelivery::Subscription(SubscriptionDelivery {
                                id,
                                event: SubscriptionDeliveryEvent::Closed,
                            }));
                        }
                        break;
                    }
                }
            }
        }
    }
}
