[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
llm = { workspace = true }
providers = { path = "../providers" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tools = { path = "../tools" }

[dev-dependencies]
futures-util = { workspace = true }
