[package]
name = "providers"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
llm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
futures-util = { workspace = true }
tokio = { workspace = true }
