//! UI-agnostic application state and event source.
//!
//! This module must not depend on ratatui or crossterm. It owns the chat
//! transcript and drives the agent. Frontends (ratatui now, gpui later) read
//! [`Controller::chat`] and listen on the event channel.

use agent::{Agent, AgentEvent, AgentStream};
use std::sync::Arc;
use std::time::{Duration, Instant};

const POLL_EVENT_LIMIT: usize = 256;
const POLL_TIME_BUDGET: Duration = Duration::from_millis(2);

/// Displayable transcript entry generated by the controller.
#[derive(Debug, Clone)]
pub enum Entry {
    Prompt(String),
    Response(String),
    Error(String),
}

/// UI-agnostic chat controller. Owns the transcript and drives the agent.
///
/// A background task streams agent events. The frontend drains them via
/// [`Self::poll`], which appends incremental text to the transcript and reports
/// the newest outcome.
pub struct Controller {
    agent: Arc<Agent>,
    chat: Vec<Entry>,
    stream: Option<AgentStream>,
    busy: bool,
    aborting: bool,
}

/// Outcome of a [`Controller::poll`] pass.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Poll {
    /// Nothing new.
    Idle,
    /// Transcript text changed (deltas appended or response entry created).
    Changed,
    /// Agent finished normally.
    Finished,
    /// Agent reported an error.
    Error,
    /// Current request was cancelled by user.
    Aborted,
}

impl Poll {
    fn combine(self, other: Self) -> Self {
        match (self, other) {
            (Self::Error, _) | (_, Self::Error) => Self::Error,
            (Self::Aborted, _) | (_, Self::Aborted) => Self::Aborted,
            (Self::Finished, _) | (_, Self::Finished) => Self::Finished,
            (Self::Changed, _) | (_, Self::Changed) => Self::Changed,
            _ => Self::Idle,
        }
    }
}

impl Controller {
    pub fn new(agent: Agent) -> Self {
        Self {
            agent: Arc::new(agent),
            chat: Vec::new(),
            stream: None,
            busy: false,
            aborting: false,
        }
    }

    /// Snapshot of the transcript.
    pub fn chat(&self) -> &[Entry] {
        &self.chat
    }

    pub fn is_busy(&self) -> bool {
        self.busy
    }

    /// Drain currently available agent events. Returns strongest outcome.
    ///
    /// Uses event and time budgets so fast streams cannot starve terminal input
    /// or rendering. Adjacent text deltas are coalesced before transcript update.
    pub fn poll(&mut self) -> Poll {
        let Some(mut stream) = self.stream.take() else {
            return Poll::Idle;
        };
        let started = Instant::now();
        let mut outcome = Poll::Idle;
        let mut processed = 0;
        let mut pending_text = String::new();

        while processed < POLL_EVENT_LIMIT && started.elapsed() < POLL_TIME_BUDGET {
            match stream.try_recv() {
                Ok(Ok(AgentEvent::TextDelta(text))) => {
                    pending_text.push_str(&text);
                    processed += 1;
                }
                Ok(Ok(AgentEvent::Finished)) => {
                    Self::append_delta(&mut self.chat, &pending_text);
                    pending_text.clear();
                    Self::ensure_response_entry(&mut self.chat);
                    self.busy = false;
                    outcome = outcome.combine(Poll::Finished);
                    break;
                }
                Ok(Err(error)) => {
                    Self::append_delta(&mut self.chat, &pending_text);
                    pending_text.clear();
                    self.busy = false;
                    if matches!(error, agent::AgentError::Aborted) || self.aborting {
                        self.aborting = false;
                        outcome = outcome.combine(Poll::Aborted);
                    } else {
                        self.chat.push(Entry::Error(error.to_string()));
                        outcome = Poll::Error;
                    }
                    break;
                }
                Err(tokio::sync::mpsc::error::TryRecvError::Empty) => break,
                Err(tokio::sync::mpsc::error::TryRecvError::Disconnected) => {
                    Self::append_delta(&mut self.chat, &pending_text);
                    pending_text.clear();
                    self.busy = false;
                    if self.aborting {
                        self.aborting = false;
                        outcome = outcome.combine(Poll::Aborted);
                    } else {
                        self.chat
                            .push(Entry::Error("agent stream disconnected".into()));
                        outcome = Poll::Error;
                    }
                    break;
                }
            }
        }

        if !pending_text.is_empty() {
            Self::append_delta(&mut self.chat, &pending_text);
            outcome = outcome.combine(Poll::Changed);
        }

        if self.busy {
            self.stream = Some(stream);
        }
        outcome
    }

    /// Submit user prompt. No-op while request is in flight.
    pub fn submit(&mut self, text: String) {
        let text = text.trim();
        if text.is_empty() || self.busy {
            return;
        }
        self.chat.push(Entry::Prompt(text.to_owned()));
        self.busy = true;
        self.stream = Some(self.agent.prompt_stream(text.to_owned()));
    }

    /// Request cancellation of current prompt.
    pub fn abort(&mut self) {
        if self.busy {
            self.aborting = true;
            if let Some(stream) = &self.stream {
                stream.abort();
            }
        }
    }

    fn append_delta(chat: &mut Vec<Entry>, delta: &str) {
        if delta.is_empty() {
            return;
        }
        match chat.last_mut() {
            Some(Entry::Response(text)) => text.push_str(delta),
            _ => chat.push(Entry::Response(delta.to_owned())),
        }
    }

    fn ensure_response_entry(chat: &mut Vec<Entry>) {
        if !matches!(chat.last(), Some(Entry::Response(_))) {
            chat.push(Entry::Response(String::new()));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use async_trait::async_trait;
    use llm::{LlmApi, LlmError, LlmEvent, StopReason};
    use providers::{
        ApiId, ModelCapabilities, ModelInfo, OpenRouterProvider, Provider, ProviderId,
    };
    use std::sync::Arc;

    struct FakeApi;

    #[async_trait]
    impl LlmApi for FakeApi {
        async fn stream(&self, request: llm::LlmRequest<'_>) -> Result<llm::LlmStream, LlmError> {
            let model = Some(request.model_id.to_owned());
            Ok(Box::pin(futures_util::stream::iter([
                Ok(LlmEvent::TextDelta { text: "hel".into() }),
                Ok(LlmEvent::TextDelta { text: "lo".into() }),
                Ok(LlmEvent::Done {
                    stop_reason: StopReason::Stop,
                    usage: None,
                    model,
                }),
            ])))
        }
    }

    fn make_controller() -> Controller {
        let info = ModelInfo {
            provider: ProviderId::new("openrouter"),
            id: "test".into(),
            name: "Test".into(),
            api: ApiId::ChatCompletions,
            capabilities: ModelCapabilities::default(),
            pricing: None,
        };
        let model = OpenRouterProvider::builder("key")
            .with_models([info])
            .with_api(Arc::new(FakeApi))
            .build()
            .unwrap()
            .bind("test")
            .unwrap();
        let agent = agent::Agent::builder(model).build();
        Controller::new(agent)
    }

    #[tokio::test]
    async fn submit_streams_incremental_text() {
        let mut controller = make_controller();
        controller.submit("hi".into());

        // Allow background task to produce all events.
        tokio::time::sleep(std::time::Duration::from_millis(50)).await;

        // One poll drains queued deltas and completion event.
        assert_eq!(controller.poll(), Poll::Finished);

        let transcript = controller.chat();
        assert_eq!(transcript.len(), 2);
        assert!(matches!(&transcript[0], Entry::Prompt(t) if t == "hi"));
        assert!(matches!(&transcript[1], Entry::Response(t) if t == "hello"));
        assert!(!controller.is_busy());
    }

    #[test]
    fn submit_ignores_empty_and_busy() {
        let mut controller = make_controller();
        controller.submit("   ".into());
        assert!(controller.chat().is_empty());
        assert!(!controller.is_busy());
    }
}
