//! UI-agnostic application state and event source.
//!
//! This module must not depend on ratatui or crossterm. It owns the chat
//! transcript and drives the agent. Frontends (ratatui now, gpui later) read
//! [`Controller::chat`] and listen on the event channel.

use agent::Agent;
use std::sync::{Arc, mpsc};

/// Displayable transcript entry generated by the controller.
#[derive(Debug, Clone)]
pub enum Entry {
    Prompt(String),
    Response(String),
    Error(String),
}

/// UI-agnostic chat controller. Owns the transcript and drives the agent.
///
/// A background task runs each [`Agent::prompt`]. Its outcome is delivered
/// through an mpsc channel and drained by the frontend via [`Self::poll`],
/// which appends new entries to the transcript and reports the newest event.
pub struct Controller {
    agent: Arc<Agent>,
    chat: Vec<Entry>,
    tx: mpsc::Sender<Entry>,
    rx: mpsc::Receiver<Entry>,
    busy: bool,
}

/// Outcome of a [`Controller::poll`] pass.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Poll {
    /// Nothing new.
    Idle,
    /// A reply was appended.
    Reply,
    /// An error entry was appended.
    Error,
}

impl Controller {
    pub fn new(agent: Agent) -> Self {
        let (tx, rx) = mpsc::channel();
        Self {
            agent: Arc::new(agent),
            chat: Vec::new(),
            tx,
            rx,
            busy: false,
        }
    }

    /// Snapshot of the transcript.
    pub fn chat(&self) -> &[Entry] {
        &self.chat
    }

    pub fn is_busy(&self) -> bool {
        self.busy
    }

    /// Drain pending entries into the transcript. Returns the newest outcome.
    pub fn poll(&mut self) -> Poll {
        let mut version: Poll = Poll::Idle;
        while let Ok(entry) = self.rx.try_recv() {
            match entry {
                Entry::Response(_) => {
                    version = Poll::Reply;
                    self.chat.push(entry);
                }
                Entry::Error(_) => {
                    version = Poll::Error;
                    self.chat.push(entry);
                }
                Entry::Prompt(_) => self.chat.push(entry),
            }
        }
        if version != Poll::Idle {
            self.busy = false;
        }
        version
    }

    /// Submit a user prompt. No-op while a request is in flight.
    pub fn submit(&mut self, text: String) {
        let text = text.trim();
        if text.is_empty() || self.busy {
            return;
        }
        self.chat.push(Entry::Prompt(text.to_owned()));
        self.busy = true;

        let agent = self.agent.clone();
        let tx = self.tx.clone();
        let text = text.to_owned();
        tokio::spawn(async move {
            match agent.prompt(text).await {
                Ok(reply) => {
                    let _ = tx.send(Entry::Response(reply.text()));
                }
                Err(err) => {
                    let _ = tx.send(Entry::Error(err.to_string()));
                }
            }
        });
    }
}
